---
global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: "local-monitor"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: node-exporter
    static_configs:
      - targets:
          - nodeexporter_server:9100


